import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrainCircuit,Crown,LogIn,Play,Plus,Settings,Shield,SkipForward,Sparkles,Users,X,Zap} from 'lucide-react';
import './styles.css';

type Question={id:string;text:string;options:string[];correct:number};
type Team={id:string,name:string,score:number,aiUsed?:number,answer?:number,correct?:boolean,answeredAt?:number,fastest?:boolean};
type Phase='idle'|'lobby'|'question'|'reveal'|'leaderboard'|'finished';
type Game={phase:Phase,questions:Question[],index:number,teams:Team[],double:boolean,updated:number};
const seed:Question[]=[
 {id:'1',text:'ما هو الكوكب المعروف بالكوكب الأحمر؟',options:['الزهرة','المريخ','المشتري','عطارد'],correct:1},
 {id:'2',text:'كم عدد أضلاع الشكل السداسي؟',options:['خمسة','ستة','سبعة','ثمانية'],correct:1},
 {id:'3',text:'ما عاصمة المملكة العربية السعودية؟',options:['جدة','الدمام','الرياض','أبها'],correct:2}
];
const initial:Game={phase:'idle',questions:seed,index:0,teams:[],double:false,updated:Date.now()};
const KEY='alkawaser-game-v1';
function load():Game{try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||'null')}}catch{return initial}}
function save(g:Game){const v={...g,updated:Date.now()};localStorage.setItem(KEY,JSON.stringify(v));window.dispatchEvent(new Event('game-update'));return fetch('/api/game',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(v)}).catch(()=>null)}
async function syncGame(setter:(g:Game)=>void){try{const r=await fetch('/api/game');if(r.ok){const remote=await r.json();if(remote?.updated){localStorage.setItem(KEY,JSON.stringify(remote));setter(remote)}}}catch{}}
const letters=['أ','ب','ج','د'];

function Logo(){return <div className="logo" aria-label="مسابقة الكواسر"><img className="logo-image" src="/alkawaser-logo.jpg" alt="شعار الكواسر"/><div><b>مسابقة الكواسر</b><small>كواسرنا لا تعرف الانكسار</small></div></div>}
function Shell({children,compact=false}:{children:React.ReactNode,compact?:boolean}){return <main className={compact?'shell compact':'shell'} dir="rtl"><header><Logo/><div className="live"><i/> مباشر</div></header>{children}<footer>مسابقة الكواسر · جاهزون للتحدّي؟</footer></main>}

function Home({go}:{go:(x:string)=>void}){return <Shell><section className="hero"><div className="eyebrow"><Sparkles size={17}/> الحماس يبدأ من هنا</div><h1>من هي الأسرة<br/><em>الأكثر معرفة؟</em></h1><p>اجتمعوا، اختاروا إجابتكم، واصعدوا إلى قمة الكواسر.</p><div className="home-actions"><button className="primary jumbo" onClick={()=>go('join')}><LogIn/> دخول المسابقة</button></div><div className="stats"><span><b>٣</b> فرص للمساعد الذكي</span><span><b>×٢</b> جولة مضاعفة</span><span><b>١</b> نقطة لكل إجابة</span></div></section><div className="orb one"/><div className="orb two"/></Shell>}

function Join({go}:{go:(x:string)=>void}){const [name,setName]=useState('');const [error,setError]=useState('');const [joining,setJoining]=useState(false);const join=async()=>{const n=name.trim();if(!n)return setError('اكتب اسم الأسرة أولًا');setJoining(true);try{const team={id:crypto.randomUUID(),name:n,score:0,aiUsed:0};const r=await fetch('/api/game/join',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({team,initial:load()})});const data=await r.json();if(!r.ok)throw new Error(data.error);localStorage.setItem(KEY,JSON.stringify(data.game));localStorage.setItem('alkawaser-team',data.team.id);window.dispatchEvent(new Event('game-update'));go('play')}catch(e:any){setError(e.message||'تعذّر الانضمام، حاول مرة أخرى')}finally{setJoining(false)}};return <Shell compact><section className="card join-card"><div className="big-icon"><Users/></div><h1>دخول الأسر</h1><p>اكتبوا اسم الأسرة كما تريدون ظهوره في لوحة الصدارة.</p><label>اسم الأسرة</label><input autoFocus maxLength={28} value={name} onChange={e=>{setName(e.target.value);setError('')}} onKeyDown={e=>e.key==='Enter'&&!joining&&join()} placeholder="مثال: أسرة الصقور"/><small className="error">{error}</small><button className="primary" disabled={joining} onClick={join}>{joining?'جارٍ الانضمام…':'انضموا الآن'} <LogIn/></button><button className="link" onClick={()=>go('home')}>العودة للرئيسية</button></section></Shell>}

function Board({teams}:{teams:Team[]}){const sorted=[...teams].sort((a,b)=>b.score-a.score);const admin=location.hash==='#admin';const kick=(id:string)=>{if(confirm('هل تريد طرد هذا الفريق؟'))save({...load(),teams:load().teams.filter(t=>t.id!==id)})};return <div className="board">{sorted.length===0?<div className="empty">لا توجد أسر منضمة بعد</div>:sorted.map((t,i)=><div className={'rank r'+i} key={t.id}><span className="place">{i===0?<Crown/>:i+1}</span><b>{t.name}{t.fastest&&<small className="speed-tag">⚡ الأسرع</small>}</b><strong>{t.score}<small> نقطة</small></strong>{admin&&<button className="kick-team" onClick={()=>kick(t.id)}><X/> طرد الفريق</button>}</div>)}</div>}

function AiModal({close,onUse,used}:{close:()=>void,onUse:(s:string)=>Promise<void>,used:number}){const [msg,setMsg]=useState('');const [sending,setSending]=useState(false);return <div className="modal-back"><div className="ai-modal"><button className="close" onClick={close}><X/></button><BrainCircuit className="brain"/><span className="pill">المساعدة {3-used} من 3</span><h2>اسأل الذكالي</h2><p>لديك رسالة واحدة فقط في هذه المحاولة. اكتبها بعناية!</p><div className="ai-warning"><b>تنبيه:</b> الذكالي مجرد ذكاء اصطناعي، وقد يخطئ. لا تعتمدوا على إجابته بشكل كامل.</div><textarea maxLength={180} disabled={sending} value={msg} onChange={e=>setMsg(e.target.value)} placeholder="مثال: ساعدني باستبعاد خيارين..."/><div className="notice">⚠️ بعد الإرسال لا يمكنك تعديل رسالتك</div><button className="primary" disabled={!msg.trim()||sending} onClick={async()=>{setSending(true);await onUse(msg)}}>{sending?'الذكالي يفكر…':'إرسال الرسالة'}</button></div></div>}

function Play({go}:{go:(x:string)=>void}){const [g,setG]=useState(load);const [ai,setAi]=useState(false);const [hint,setHint]=useState('');const id=localStorage.getItem('alkawaser-team');useEffect(()=>{const u=()=>setG(load());addEventListener('storage',u);addEventListener('game-update',u);const timer=setInterval(u,1200);return()=>{removeEventListener('storage',u);removeEventListener('game-update',u);clearInterval(timer)}},[]);useEffect(()=>setHint(''),[g.index]);const team=g.teams.find(t=>t.id===id);if(!team)return <Join go={go}/>;const used=Number(team.aiUsed)||0;const q=g.questions[g.index];const answer=async(i:number)=>{if(g.phase!=='question'||team.answer!==undefined)return;const optimistic={...g,teams:g.teams.map(t=>t.id===id?{...t,answer:i}:t)};localStorage.setItem(KEY,JSON.stringify(optimistic));window.dispatchEvent(new Event('game-update'));try{const r=await fetch('/api/game/answer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({teamId:id,answer:i})});if(r.ok){const remote=await r.json();localStorage.setItem(KEY,JSON.stringify(remote));window.dispatchEvent(new Event('game-update'))}}catch{}};const ask=async(message:string)=>{try{const res=await fetch('/api/gemini',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({teamId:id,message})});const data=await res.json();if(data.game){localStorage.setItem(KEY,JSON.stringify(data.game));setG(data.game);window.dispatchEvent(new Event('game-update'))}setHint(data.text||data.error||'تعذّر سؤال الذكالي الآن.')}catch{setHint('تعذّر سؤال الذكالي الآن.')}finally{setAi(false)}};
 if(g.phase==='idle')return <Shell compact><section className="wait"><div className="pulse"><Crown/></div><h1>لم تبدأ المسابقة بعد</h1><p>تم تسجيل <b>{team.name}</b>. ابقوا في هذه الصفحة، ستظهر اللعبة تلقائيًا عندما يبدأ الأدمن.</p><div className="waiting"><i/> في انتظار بدء المسابقة...</div></section></Shell>;
 if(g.phase==='lobby')return <Shell compact><section className="wait"><div className="pulse"><Users/></div><h1>استعدوا يا {team.name}!</h1><p>الأسر تتجمع الآن في ميدان التحدّي</p><Board teams={g.teams}/></section></Shell>;
 if(g.phase==='leaderboard'||g.phase==='finished')return <Shell compact><section className="leader"><div className="eyebrow"><Crown/> لوحة الصدارة</div><h1>{g.phase==='finished'?'أبطال الكواسر':'الترتيب الحالي'}</h1><Board teams={g.teams}/><p className="waiting"><i/> {g.phase==='finished'?'انتهت المسابقة':'السؤال التالي بعد قليل...'}</p></section></Shell>;
 return <Shell compact><section className="question phone-pad"><div className="q-top"><span>السؤال {g.index+1}</span>{g.double&&<b className="double"><Zap/> دبل</b>}<strong>{team.score} نقطة</strong></div><p className="look-up">شاهدوا السؤال على شاشة العرض</p>{hint&&<div className="hint"><BrainCircuit/>{hint}</div>}<div className="mobile-answers">{q.options.map((_,i)=>{const chosen=team.answer===i;const reveal=g.phase==='reveal';return <button key={i} aria-label={'الإجابة '+letters[i]} onClick={()=>answer(i)} disabled={team.answer!==undefined||reveal} className={(chosen?'chosen ':'')+(reveal?(i===q.correct?'correct':chosen?'wrong':''):'')}>{letters[i]}</button>})}</div>{g.phase==='question'&&team.answer===undefined&&<button className="ai-help" disabled={used>=3} onClick={()=>setAi(true)}><BrainCircuit/> اسأل الذكالي <small>{3-used} متبقية</small></button>}{g.phase==='question'&&team.answer!==undefined&&<div className="locked">تم تثبيت إجابتكم… بالتوفيق!</div>}{g.phase==='reveal'&&<div className="reveal-msg">{team.answer===q.correct?'🔥 إجابة صحيحة! يا كواسر':'الإجابة الصحيحة هي '+letters[q.correct]+' — عوّضوها في القادم!'}</div>}{ai&&<AiModal close={()=>setAi(false)} onUse={ask} used={used}/>}</section></Shell>}

function Screen(){const [g,setG]=useState(load);useEffect(()=>{const u=()=>setG(load());addEventListener('storage',u);addEventListener('game-update',u);const timer=setInterval(u,1000);return()=>{removeEventListener('storage',u);removeEventListener('game-update',u);clearInterval(timer)}},[]);const q=g.questions[g.index];const fastest=g.teams.find(t=>t.fastest);if(g.phase==='idle')return <Shell><section className="screen-wait"><img src="/alkawaser-logo.jpg" alt="شعار الكواسر"/><h1>مسابقة الكواسر</h1><p>المسابقة لم تبدأ بعد</p></section></Shell>;if(g.phase==='lobby')return <Shell><section className="screen-board"><div className="eyebrow"><Users/> الأسر مستعدة</div><h1>مرحبًا بالكواسر</h1><Board teams={g.teams}/></section></Shell>;if(g.phase==='leaderboard'||g.phase==='finished')return <Shell><section className="screen-board"><div className="eyebrow"><Crown/> لوحة الصدارة</div><h1>{g.phase==='finished'?'أبطال الكواسر':'الترتيب بعد السؤال'}</h1><Board teams={g.teams}/></section></Shell>;return <Shell><section className="projector-question"><div className="q-top"><span>السؤال {g.index+1} من {g.questions.length}</span>{g.double&&<b className="double"><Zap/> نقاط مضاعفة</b>}<strong>{g.teams.filter(t=>t.answer!==undefined).length} / {g.teams.length} أجابوا</strong></div>{g.phase==='reveal'&&fastest&&<div className="fastest-banner">⚡ أسرع إجابة صحيحة: {fastest.name}</div>}<h1>{q.text}</h1><div className="projector-answers">{q.options.map((o,i)=>{const picked=g.teams.filter(t=>t.answer===i);return <div key={o} className={g.phase==='reveal'?(i===q.correct?'correct':'dim'):''}><div className="answer-line"><span>{letters[i]}</span><b>{o}</b>{g.phase==='reveal'&&i===q.correct&&<strong>الإجابة الصحيحة ✓</strong>}</div>{g.phase==='reveal'&&picked.length>0&&<div className="picked-teams">{picked.map(t=><em key={t.id}>{t.name}{t.fastest&&' ⚡ الأسرع'}</em>)}</div>}</div>})}</div></section></Shell>}

function Admin({go}:{go:(x:string)=>void}){const [g,setG]=useState(load);const [editing,setEditing]=useState<number|null>(null);useEffect(()=>{const u=()=>setG(load());addEventListener('storage',u);addEventListener('game-update',u);return()=>{removeEventListener('storage',u);removeEventListener('game-update',u)}},[]);const commit=(n:Game)=>{setG(n);save(n)};const start=()=>commit({...g,phase:'lobby',index:0,teams:g.teams.map(t=>({...t,score:0,aiUsed:0,answer:undefined,correct:undefined}))});const show=()=>commit({...g,phase:'question',teams:g.teams.map(t=>({...t,answer:undefined,correct:undefined}))});const reveal=()=>{const q=g.questions[g.index];commit({...g,phase:'reveal',teams:g.teams.map(t=>{const ok=t.answer===q.correct;return {...t,correct:ok,score:t.score+(ok?(g.double?2:1):0)}})} )};const leaderboard=()=>commit({...g,phase:'leaderboard'});const next=()=>{if(g.index+1>=g.questions.length)commit({...g,phase:'finished'});else commit({...g,index:g.index+1,phase:'question',double:false,teams:g.teams.map(t=>({...t,answer:undefined,correct:undefined}))})};const updateQ=(i:number,key:string,val:any)=>{const qs=[...g.questions];qs[i]={...qs[i],[key]:val};commit({...g,questions:qs})};const add=()=>{commit({...g,questions:[...g.questions,{id:crypto.randomUUID(),text:'سؤال جديد',options:['الخيار الأول','الخيار الثاني','الخيار الثالث','الخيار الرابع'],correct:0}]});setEditing(g.questions.length)};
 return <Shell><div className="admin-head"><div><div className="eyebrow"><Settings/> غرفة التحكّم</div><h1>لوحة قائد المسابقة</h1></div><button className="ghost" onClick={()=>go('home')}>عرض الرئيسية</button></div><div className="admin-grid"><section className="control card"><div className="section-title"><h2>التحكم المباشر</h2><span className={'status '+g.phase}>{g.phase==='idle'?'غير مبدوءة':g.phase==='lobby'?'تجهيز':g.phase==='question'?'السؤال ظاهر':g.phase==='reveal'?'كشف الإجابة':g.phase==='leaderboard'?'الصدارة':'انتهت'}</span></div><div className="current"><small>السؤال الحالي</small><b>{g.questions[g.index]?.text}</b></div><label className="switch"><input type="checkbox" checked={g.double} onChange={e=>commit({...g,double:e.target.checked})}/><span/> <Zap/> دبل النقاط لهذا السؤال</label><div className="control-actions">{g.phase==='idle'&&<button className="primary" onClick={start}><Play/> ابدأ المسابقة</button>}{g.phase==='lobby'&&<button className="primary" onClick={show}><Play/> اعرض السؤال الأول</button>}{g.phase==='question'&&<button className="primary hot" onClick={reveal}><Sparkles/> اكشف الإجابات والصحيح</button>}{g.phase==='reveal'&&<button className="primary" onClick={leaderboard}><Crown/> اعرض الصدارة</button>}{g.phase==='leaderboard'&&<button className="primary" onClick={next}><SkipForward/> السؤال التالي</button>}{g.phase==='finished'&&<button className="primary" onClick={start}>مسابقة جديدة</button>}</div><div className="mini-board"><h3><Users/> الأسر المنضمة <span>{g.teams.length}</span></h3><Board teams={g.teams}/></div></section><section className="questions card"><div className="section-title"><h2>بنك الأسئلة</h2><button className="icon-btn" onClick={add}><Plus/> سؤال</button></div><div className="q-list">{g.questions.map((q,i)=><div className="q-edit" key={q.id}><button className="q-summary" onClick={()=>setEditing(editing===i?null:i)}><span>{i+1}</span><b>{q.text}</b><small>{i===g.index?'الحالي':'تعديل'}</small></button>{editing===i&&<div className="editor"><label>نص السؤال<input value={q.text} onChange={e=>updateQ(i,'text',e.target.value)}/></label>{q.options.map((o,j)=><label className="option-edit" key={j}><input type="radio" name={'correct'+i} checked={q.correct===j} onChange={()=>updateQ(i,'correct',j)}/><input value={o} onChange={e=>{const ops=[...q.options];ops[j]=e.target.value;updateQ(i,'options',ops)}}/></label>)}<button className="link" onClick={()=>setEditing(null)}>تم الحفظ</button></div>}</div>)}</div></section></div></Shell>}

function RemoteSync(){useEffect(()=>{const pull=async()=>{try{const r=await fetch('/api/game',{cache:'no-store'});if(r.ok){const remote=await r.json();if(remote?.updated&&remote.updated!==load().updated){localStorage.setItem(KEY,JSON.stringify(remote));window.dispatchEvent(new Event('game-update'))}}}catch{}};pull();const timer=setInterval(pull,900);return()=>clearInterval(timer)},[]);return null}
function App(){const [page,setPage]=useState(location.hash.slice(1)||'home');const go=(p:string)=>{location.hash=p;setPage(p)};useEffect(()=>{const h=()=>setPage(location.hash.slice(1)||'home');addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);const view=page==='join'?<Join go={go}/>:page==='play'?<Play go={go}/>:page==='screen'?<Screen/>:page==='admin'?<Admin go={go}/>:<Home go={go}/>;return <><RemoteSync/>{view}</>}
createRoot(document.getElementById('root')!).render(<App/>);
